# Generated by Django 4.0.4 on 2022-05-26 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_genre_alter_movie_movie_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentedMovie',
            new_name='RentMovie',
        ),
    ]
